### ISSUE TITLE
你好，对你的工作很感兴趣

### ISSUE THREAD

**Issue by storm-zhuo** [lk485/matgcn#2]
我是初学者，刚刚踏入这个领域，请问这个代码应该怎么用呢？我直接运行main.py 会报错    assert len(sys.argv) >= 2
AssertionError

**Comment by danranyiyu123456** [comment]
同样的错误，希望您能够提供一个代码运行的解释文件，非常感谢

**Comment by luokn** [comment]
你需要下载数据集，PEMS04和PEMS08，链接已放在README.md里面

**Comment by lk485** [comment]
.
