### ISSUE TITLE
G attention

### ISSUE THREAD

**Issue by whf9527** [lk485/matgcn#4]
torch.softmax(k @ self.W @ q.transpose(1, 2), dim=-1)  # [B, N, N] 
你好，想问一下怎么理解这段代码的意义。他与pyGAT的实现两点间的注意力权重【n, n】存在区别。

**Comment by luokn** [comment]
这里用的是带参数的点积注意力
发件人: ***@***.***>
发送时间: 2021年8月2日 21:43
收件人: ***@***.***>
抄送: ***@***.***>
主题: [luokn/matgcn] G attention (#4)


torch.softmax(k @ self.W @ q.transpose(1, 2), dim=-1) # [B, N, N]
你好，想问一下怎么理解这段代码的意义。他与pyGAT的实现两点间的注意力权重【n, n】存在区别。

―

**Comment by luokn** [comment]
这是基于点积的注意力机制，可以参考一下论文《Attention Is All You Need》
